name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  postgres: ^3.2.1
  flutter_dotenv: ^5.1.0
  schema_dart: ^0.0.5
  supabase_flutter: 2.5.6
  google_sign_in: ^6.2.1
  nb_utils: ^7.0.3
  mobx: ^2.3.3+2
  image_picker: ^0.8.1+3
  path_drawing: ^1.0.1
  table_calendar: ^3.0.0
  flutter_local_notifications: ^17.2.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
  mobx_codegen: ^2.0.5+2
  flutter_launcher_icons: ^0.9.2
  
  

  


flutter:
  uses-material-design: true
  assets:
  - assets/images/dino_reichmuth_a_5_rcn_8626_ck_unsplash_1.jpeg
  - assets/vectors/vector_x2.svg
  - assets/vectors/clip_path_group_x2.svg
  - assets/vectors/rectangle_4_x2.svg
  - assets/vectors/rectangle_41_x2.svg
  - images/

